### ISSUE TITLE
En verder!

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#10]
Hi @maartenmarx , 

Inmiddels een beetje hersteld?

Ik twijfel nog een beetje over mijn onderzoeksvraag. Zoals hij in het voorstel geformuleerd staat: "How can an information request be digitally represented and standardized to empower the concept of an open government?”. Geeft dat laatste stukje niet aan dat ik eigenlijk zou moeten toetsen dat de representatie daadwerkelijk bijdraagt aan een open overheid? RQ1 (What ‘open data’ factors make a government ‘open’?) is ook een beetje vreemd naar mijn idee, aangezien dat verder ook helemaal niet terug komt en ook niet te onderzoeken is of het schema daadwerkelijk helpt. Dat is namelijk niet helemaal de bedoeling van het onderzoek, aangezien het meer een soort aanbeveling is, of exploratief onderzoek. Ik vind het daarom lastig om hiervoor een goede onderzoeksvraag te bedenken. Aangezien je vast wel eens meer van dit soort onderzoeksopzetten hebt gezien; heb je een advies?

Misschien kunnen we ergens volgende week oid nog eens een keertje meeten om de uitlijning van het onderzoek goed vast te leggen. Ik vind het fijn om dat even goed overzichtelijk te hebben.

Met vriendelijke groet,
Maik

**Comment by maartenmarx** [comment]
Hi @maiklarooij , heel goed dat je hier zo mee bezig bent. Mijn herstel gaat erg langzaam, maar god zij dank had ik het ook niet heel erg. Maar goed, 1 trap oploppen en krom staan van het hijgen, jongen, wat een ramp. 

Ja, die vraag vond ik al meteen veel te hoogdravend, maar dat geeft niet, maak nou maar eerst goede deelvragen en ook nog deeldeelvragen. Dan verzin je daar aan het eind heel makkelijk de overkoepelende vraag bij.

Deel vraag 1: het schema, en hoe dat kan helpen bij de productie en publicatie
 1.1: het schema
  1.2 de productie
  1.3 de publicatie

Het schema heb je vrijwel af. Maak nu die "software" waarmee je vrijwel moeiteloos bijna autoamtische alles netjes in dat schema plaatst. En toets het.

En maak dan een manier van publiceren. Gewoon simpel, bijv je leest je json in als spreadsheet in pandas, rommelt wat en public eert het met `to_html()`, en schrijft de dingen netjes weg zodat je fijn kan klikken, en je maakt een tijdslijntje, en weet ik wat. Als je de twitter css gebruikt ziet het er meteen heel gelikt uit, maar dat hoeft allemaal niet. 

Je evelueert dat op 2 manieren:

1. check zelf dat alles in het schema nu ook op die "webpagina" staat. 
2. Ga een lijstje met functionalietit af (bijv: ordenen van de docs op filenaam, en chronologisch), weet ik wat,
3. Laat iemand van FTM er eens mee spelen (via Filipp). Uit het stuk van Filipp kan je meteen halen wat zij heel graag willen: alles waar ze nu zoveel moeite voor doen ;-) Dus dat wordt een jubelevaluatie ;-)

Deelvraag 2  kan dan gaan over de "winst" in informatie die je zo kan behalen. Hier kan je ook je OCR vs pdftotext spul kwijt.

En 3 over het inzetten in een zoeksysteem (dus waarbij je verder kijkt dan 1 wobverzoek plus antwoord).

Is dat wat?

Ja toch?

groet
maarten

PS Probeer deel 1 alvast eens op te schrijven: in ieder geval het skelet ervan.

**Comment by maiklarooij** [comment]
Hi @maartenmarx ,

Ja, dat virus is een flinke aantasting op de conditie haha. Gelukkig is het aan de betere hand.

Dit klinkt als een goed begin. Op die manier kan ik het zelf allemaal wat beter ordenen. Ik ben van plan om misschien vanaf volgende week (of ergens daarna) een stuk actiever eraan te gaan werken, zodat ik gewoon lekker door kan werken. Misschien ben ik dan een stuk eerder klaar dan 24 juni. Dat is sowieso natuurlijk niet erg, maar het gesukkel van 'af en toe een paar uurtjes' ergens tussendoor in de week werkt niet zo goed voor mij. Het leek me goed om dat even te laten weten. 

Hoe zie je deel 3 over inzetten in een zoeksysteem precies voor je? Eigenlijk wat Sam aan het doen is?

Groetjes,
Maik

**Comment by maartenmarx** [comment]
@maiklarooij , heel goed joh. Lekker de vaart erin! Dat deel 3, ja, probeer er een eigen richting/deel in te vinden/pakken.

Je zou kunnen denken aan functionaliteit die wat meer gebruik maakt van jouw metadata in jouw schema (facetten, tijdslijn, weet ik wat), en dat Sam zich meer richt op de text inhoud. Is dat wat? 

Ik denk dat het vooral gaaf is om te laten zien wat je allemaal kunt met al die json data ion jouw schema. Een mooie zoekmachine interface geef dat prachtig weer. Je kan dat al heel snel en leuk maken in een notebook met widgets.

**Comment by maiklarooij** [comment]
@maartenmarx heel fijn. Ik ga me volgende week eerst eens richten op het (deels) schrijven van het eerste deel over het schema en het maken van de automatische productie van de publicaties. Misschien vallen dan ook meer dingen op zijn plek, zoals passende vragen. To be continued...

**Comment by maartenmarx** [comment]
@maiklarooij , voor je kwaliteitsmeting is het openstate corpus wat sam heeft opgehaald natuurlijk ideaal, want dan kan je een prachtige "appendix" aan hun rappoprt schrijven, waarin je heel droog weergeeft wat de FTM mensen ook al zeiden in het rappprt van Filipp. Openstate samen met het covid corpus is ook heel mooi. Het leuke is dat je dan mooi groupby's kunt doen en allicht is er ook een ministerie dat het wel netjes doet (alhoewel .....). 

Hadden jullie nog gekeken naar het OCR script van Fajar voor openstate? Iemand uit de doc splitting groep had het wel aan de praat gekregen. Het staat op de gemeenschappijle wobir repo.

succes
maarten

**Comment by maiklarooij** [comment]
@maartenmarx ik ga binnenkort inderdaad eens even een heerlijk corpus samenstellen voor de kwaliteitsmeting. Op dit moment ben ik bezig met schrijven over het schema. Mijn plan is om de attributen uit verschillende bronnen te laten komen.

- Metadata standaarden (Dublin Core), voor de echte basis info
- Journalistieke standaard (FTM), voor een meer eindgebruikers approach
- Eerder werk van OpenState (handreiking), deze is in samenwerking met provincie en gemeenten
- Eigen analyse van gepubliceerde stukken (rijksoverheid.com/documenten, https://www.utrecht.nl/bestuur-en-organisatie/publicaties/openbaar-gemaakte-informatie-na-wob-verzoeken)
- Vanuit een meer academisch/onderzoeksperspectief: dingen als aantal woorden, aantal tekstpagina's

Ik hang een beetje vast bij het vierde punt. Hoe uitgebreid kan ik dat het beste doen? Hoe kan ik toch onderbouwen dat die attributen noodzakelijk zijn?
- Heb ik dan een groot corpus nodig waarin ik laat zien dat bijv. elk verzoek een titel heeft, en dan ook laten zien hoe dat in gemeenten/provincies zit
- Of is het goed genoeg om te benoemen dat ik heb geobserveerd dat de publicaties redelijk gestandardiseerd worden vormgegeven, waardoor ze altijd een titel hebben en dat dus ook van belang is voor in het schema
Bij de eerdere punten kon ik gewoon lekker refereren naar die literatuur of ISO norm, om vervolgens daar attributen uit te pakken, maar nu moet ik met meer 'eigen' gevonden attributen komen. Kortom, in hoeverre moet ik beschrijven/aantonen hoe ik bij de informatie en attributen kom?

Bedankt alvast!

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

mooi joh. Joh, titel zit al in =Dublin Core ;-). Maar zonder gekheid, als jij kan motiveren dat/waarom een attribuut handig is, plus dat het in sommige wobs zit is dat voldoende onderbouwing.

Ik zou voor elke bullet een eigen namespace (afkorting) gebruiken. Dat groepeert het makkelijk en netjes. En zo'n namespace is feitelijk niks hoor. En je gebruikt gewoon van die afkortingen als dc: en ftm: en ml: 

doei
maarten
