### ISSUE TITLE
Binnenlands bestuur

### ISSUE THREAD

**Issue by maartenmarx** [maiklarooij/bachelorsthesis#12]
Hi @maiklarooij , Ik zat te denken aan je deel 1, en wat we daarmee zouden kunnen doen.

Misschien is het wat om je werk in het blad [binnenlands bestuur](https://www.binnenlandsbestuur.nl/bestuur-en-organisatie/wob-woo-openbaar-niet-echt-openbaar) te krijgen. Dat is iets waar alle beleidsambtenaren vanuit hun werk een abbonement op krijgen en volgens mij best veel lezen. 

Probeer eens dat rapport van dat DeFacto in handen te krijgen. 

Dit is een prachtige quote (vooral die 4 FAIR) principes)

>De Wob en de Woo zijn een uitvloeisel van artikel 110 van de Grondwet: ‘De overheid ­betracht bij de uitvoering van haar taak openbaarheid volgens regels bij de wet te stellen’. De Woo moet ervoor zorgen dat overheidsinformatie beter vindbaar, uitwisselbaar, eenvoudig te ontsluiten en goed te archiveren is.

Ik zag daar ook [dit](https://www.binnenlandsbestuur.nl/digitaal/woo-tooling-handel-snel-en-efficient-informatieverzoeken-af) en ik denk dat je moet proberen er een vrijkaartje voor te regelen. Ik schrijf graag een aanbeveling vo rje.

Als je op BB wat verder zoekt op WOO zie je dat het erg veel speelt, en ook dat commerciele partijen daar vooral over schrijven. Best raar.

Jij zou jouw bevindingen over de inventaris lijsten (interopratbiliteit heel slecht, en de machine leesbaarheid (OCR, findable heel slecht), en natuurlijk het aan elkaar geplakt zijn (idem alles slecht) hier mooi in kwijt kunnen. Gebaseerd op vet veel data, van de "beste" ambtenaren (rijksoverheid). Plus natuurlijk jouw supoer simpele software om het wel FAIR aan te bieden.

Ik heb trouwens Yunus gevraagd om alles van <https://open.overheid.nl/ZoekUitgebreidResultaat?informatiesoort=c_e0865e4d> te downloaden. Dit lijkt er wat beter uit te zien, op het eerste oog. Ik heb hem ook gezegd dat ie jouw kwaliteits software (vooral van ocr) kan gebruiken. 

### To do, wat denk je?

* kijk eens rond daar bij dat binnelands bestuur en kijk eens of je een redacteur vind die "hier over gaat" (misschien eerder via twitter oid)
* probeer je aan te melden voor die webinar van dat zylab
* Bedenk eens wat je in zo'n stuk kwijt zou willen. Misschien kan je per FAIR principe een enorme omissie klaten zien, en later een supergoede reparatie.

OK, veel plezier! Krijg ik weer eens een update?

groet
maarten

**Comment by maiklarooij** [comment]
Hi @maartenmarx ,

## Allereerst een korte update:
- Geprobeerd de feedback te verwerken op de tekst over het schema, in ieder geval de requirements -> data model en attributen loopt nu wat logischer en duidelijker
- De automatische productie van de WOBs met de simpele tool lijkt af, je kunt alles invullen en daarna wordt de input gevalideerd. De gebruiker kan vervolgens een JSON van de gehele publicatie downloaden of een CSV van de 'inventarislijst', oftewel gewoon een lijst met de documenten in de publicatie.
- Ik ben van plan om bezig te gaan met verder schrijven aan het productiestuk, dus wat na het stuk komt dat ik vorige update stuurde. Ik moet nog even goed nadenken hoe ik dat het beste kan aanpakken.
- Daarnaast het programmeergedeelte weer: nu wil ik werken aan een JSON ergens uploaden om vervolgens een 'publicatiepagina' te maken, dus waarschijnlijk weer met een tabelletje als inventarislijst en misschien nog wat leuke informatie erbij.

## Binnenlands bestuur
Wat leuk dat je dat bent tegengekomen! Ik heb in ieder geval een plekje gereserveerd voor de webinar. Een stuk in het binnenlands bestuur klinkt ontzettend gaaf. Wel uitkijken dat het stuk dan niet te technisch wordt denk ik. Ik ben wel benieuwd hoe haalbaar het is. Ik zal eens kijken of ik erachter kan komen wie de redacteuren zijn. Volgens mij gaat het stuk over dit onderzoek van Pro Facto: https://www.nvrr.nl/wp-content/uploads/2022/03/220223-Eindrapportage-NVRR-DoeMee2021-Wob-HERZIEN.pdf. Het lijkt erop dat zij vooral kijken naar het juridische aspect, dus of iedereen zich wel aan de regeltjes houdt.

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

altijd weer heerlijk je enthousiasme te proeven! 

1. Leuk dat je naar die workshop gaat. Probeer axhter de redacteur bij BB te komen die "de wob/woo doet".
2. Ik denk eigenlijk dat jouw deel 1 ook prima in [ESB](https://esb.nu/service/publiceren#artikelen) kan. De economische invalshoek is gigantische besparing op arbeidsuren en dus geld. Maar we kunne ook ander ekanten belichten. 
3. Maak nou je deel 1 eens af, en maak je grafiekjes zo helder dat "je punt ervanaf springt". Dat is toch helemaal niet technisch?  
4. Probeer het anders vanuit die FAIR data principes op te schrijven, en voor elke letter 1) een (joekel van een) belemmering aan te geven, en 2) jouw (ultrasimpele) oplossing. Je hebt dan 4 grafiekjes/tabelletjes nodig....
5. Heb je al iets over de pdftotext/woorden in de stukken? Is dat bewijs genoeg? Heb je dat uitgeslitst naar besluit/inventarislijst/documenten? 
6. Het is NU HET MOMENT! Volghens mij schrijven we dat in een dag, en dan nog een dag klooien aan de grafiekjes en de captions. 
7. Nou, kijk eens rond op ESB, en lees wat en probeer iets te vinden wat lijkt op jouw werk.

Succes! 
maarten
