### ISSUE TITLE
Automatische productie van publicaties

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#13]
Hallo @maartenmarx ,

Ik ben nu aanbeland bij het stuk over de automatische productie en validatie van de verzoeken. Ik heb nu in ieder geval het kopje over de benodigde constraints en over validatie met behulp van JSON Schema. Het lijkt me wat overweldigend om het hele JSON schema erin te zetten, dus ik dacht aan een klein voorbeeldje met een beperkt aantal attributen. Hoe kan ik nu het beste verder? Ik heb natuurlijk nu die tool gemaakt, maar plak ik dan gewoon screenshotjes ofzo erin? Hoe maak ik het toch wetenschappelijk, zoals bij het schema nu goed gelukt is door meerdere bronnen voor attributen te geven om het te onderbouwen? Ik zat zelf ook nog te denken om misschien een soort case te gebruiken (misschien Zonneweide?) om te laten zien wat het proces is van omzetten naar JSON, valideren etc.

Groetjes,
Maik

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

1. Ja joh prima om mete en voorbeeldte werken. Zet de rest in de appendix. Zijn je attributen logisch egeroupoeerd? Dat scheelt ook vaak in de overweldigendheid.
2. Over die tool: ja een screenshot is prima, en dan een verhaaltje/argument dat die volledig is, pljus handig.
3. Hetzelfde over de output kant. Zie het schema als een soort logiusche tussentaal.
4. Zo'n voorbeeld, allicht ook op het web is natuurlijkp[rachtig.
5. Heb je een css-achtige taal gevonden om zo'n schema te publiceren als html pagina? Ik dac ht via pandas toch? Maak het niet moeilijker dan het is, kies liever voor iets dat makkelijk aan te passen/uit te breiden is. De echte opmaak is niet jouw pakkie an.

ciao
maarten

**Comment by maiklarooij** [comment]
Zeker weten! Ik doe het nu inderdaad via pandas. Hij maakt dan een tabel van de documenten en een soort infobox rechts van de gehele publicatie. 
![image](https://user-images.githubusercontent.com/54892350/165325244-74d8dc8a-6848-48e0-9401-40dfc3484e34.png)
Je kunt dan een JSON downloaden of een CSV van de documenten (zelfde als die tabel) als inventarislijst. 

Dank, ik kan zo weer even verder!
