### ISSUE TITLE
meeting vandaag

### ISSUE THREAD

**Issue by maartenmarx** [maiklarooij/bachelorsthesis#14]
Hi @maiklarooij ,

Ik heb vrijdagmiddag een begin gemaakt van ons stuk voor ESB/binnenlands bestuur.
Ik wilde op 3 manieren aantonen hoe unFAIR de wob data is

1. woorden zijn er niet (het OCR verhaal)
2. docs niet geplitst
3. metadata is een soepzooitje

1.Heb jij tabellen voor punt 1 voor het openstate corpus?
2. Voor de metadata heb ik wel al wat gezien, op je eigen inventarislijst zetje.

Allicht kan je me vandaag nog even laten zien wat je hebt, zodat we een plannetje kunnen maken voor dat ESB stuk. Ik dacht Maarten de Rijke, Mister AI Nederland ook als co-autheur te vragen. Dan krijgt zo'n aanklacht opeens veel meer impact. 

Kijk eens op <https://docs.google.com/spreadsheets/d/1JK7qWe7gW_nctuEYnzsFAF8drzXQyZMHA3SoZy-XCVA/edit?usp=sharing> of er nog een gaatje is waar je in kunt.

groet
maarten

**Comment by maiklarooij** [comment]
Hi @maartenmarx ,

Goed idee. Ik kan om 9:30 wel even tussendoor!

**Comment by maiklarooij** [comment]
Is er ergens een zoom link die ik over het hoofd heb gezien?
