### ISSUE TITLE
ESB 

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#15]
@maartenmarx hierbij de ESB issue. De stukken die ik tot zover heb geschreven staan hier:
- Schema: https://github.com/maiklarooij/bachelorsthesis/blob/master/research/thesis%20parts/schemaDoc.pdf
- Automatische publicatie: https://github.com/maiklarooij/bachelorsthesis/blob/master/research/thesis%20parts/publicationDoc.pdf

De grafieken en eventuele datasets volgen nog...

**Comment by maiklarooij** [comment]
Tipje van de sluier (moet ze nog even goed opslaan en titels etc
![image](https://user-images.githubusercontent.com/54892350/166204787-8d57c1b6-47a7-4e17-912a-fceaeaeeaac9.png)

**Comment by maartenmarx** [comment]
Hi @maiklarooij , ik ga later even naar je stukken kijken, en hoe ik dat kan inpassen.
Nu alvast even mijn eerste draft <https://github.com/maiklarooij/bachelorsthesis/blob/master/research/ESB%20draft%20Fair%20Wob%20dossiers.md>

Wat vind je ervan?

groet
maarten

**Comment by maiklarooij** [comment]
Goedemorgen @maartenmarx ,

Ziet er goed uit! Drie dingen die me allereerst opvielen
- Ik denk dat we nog iets duidelijker moeten maken in de rest van het stuk aan wélke FAIR principes waarmee worden voldaan, dus er komt nu terug in het stuk dat de vier principes enorm abstract zijn, maar daarna komen ze eigenlijk individueel niet meer terug. Bijv: voorwaarde 3 zorgt voor vindbaarheid, maar ook herbruikbaarheid. Dus eigenlijk weer wat meer een terugkoppeling op die kwaliteit die genoemd is in de inleiding
- Voorwaarde 1 lijkt nog wat uitleg nodig te hebben (met de 'informatie-eendheid' en 'technische bestandseenheid'), we moeten onthouden dat het economen zijn die dit lezen en geen informatici, ik vind hem zelf al wat lastig te begijpen
- Onder 'Hoe WOB dossiers FAIR te maken' staat "en de metadata op een uniforme wijze in een spreadsheet, liefst met hyperlinks naar de losse documenten". Dat klopt niet helemaal met mijn onderzoek toch? Daar doe ik het juist niet in een spreadsheet... En de hyperlinks zijn voor ambtenaren lastig in te vullen vóór publicatie. 

## Nog een paar nuttige links naar onderzoeken
- [van Oostveen & van Loenen](https://repository.tudelft.nl/islandora/object/uuid:058adf5b-e824-4d1a-92e3-a6bbdd473998?collection=research). Gebruikersperspectief van de WOB. Takeaway: de reacties van de overheidsorganen zijn zo verschillend (gemeleerd) dat er geen lijn in de geleverde informatie is te vinden.
- [Actieplan open overheid 2020-2022](https://www.open-overheid.nl/actieplan-open-overheid-2020-2022/). Takeaway: de wens voor open-wob standaarden om makkelijker overheidsinformatie te publiceren.
- [Berenschot](https://www.informatiehuishouding.nl/binaries/informatiehuishouding/documenten/rapporten/2021/04/07/verbeterpunten-informatiehuishouding-wob_rddi/Rapport+Berenschot+Verbeterpunten+IHH+ivm+goede+afhandeling+WOB-verzoeken.pdf) volgens mij is dit dat rapport van Berenschot.

## Mijn taken
- Hierboven stuurde ik al kort een grafiek met het aantal woorden per optie. Deze zal ik nog even finetunen.
- Ik heb even gekeken naar een histogram waarin we de hoeveelheid kolommen kunnen neerzetten. Dit ziet er leuk uit, maar ik twijfel nog even over de validiteit omdat er bijvoorbeeld ook wel eens tabellen 90 graden gedraaid staan, wat resulteert in 12 kolommen omdat hij dan eigenlijk het aantal rijen telt... Of redelijk vaak 1 kolom omdat, hoewel ik wel wat heb ingebouwd om dit te voorkomen, soms de tabel zo'n vreemde structuur heeft dat hij niet de rij met de kolomnamen pakt maar een lege rij. Ik zie zo 123 even niet hoe we dit kunnen oplossen. Gewoon accepteren en benoemen dat het sowieso slecht te lezen is? Ideeën? 
- We wilden kijken hoeveel van de Openstate pdf's niet te lezen waren (met pdftotext). Ik heb wel de data gevonden, maar deze zijn helaas nog wel op WOB niveau. Dat betekent dat ik eerst zelf weer de pdf's moet downloaden, wat waarschijnlijk best simpel kan maar ik geloof dat we deze pdf al ergens hadden toch? Had Sam die niet al? Ik lijk de toegang tot Surf helaas verloren te zijn... 
![image](https://user-images.githubusercontent.com/54892350/166887097-f4f693ba-ee7d-49a8-8e32-d7db1d51a499.png)

**Comment by maartenmarx** [comment]
Hi Maik,

Ik reageer later even uitgebreid, maar hier de link naar de openstate wobs: https://surfdrive.surf.nl/files/index.php/s/qPJrI24TZVGtlPg

Dat is groot hoor!
Dank!!

Met vriendelijke groeten,

Maarten Marx

Die Philosophen haben die Welt nur verschieden interpretiert; es kommt drauf an, sie zu verändern.

A wealth of information creates a poverty of attention. (H.A. Simon)

***@***.******@***.***> +31 06 400 16 120  IRlab Informatics Institute Universiteit van Amsterdam




On May 5, 2022, at 10:31 AM, Maik Larooij ***@***.******@***.***>> wrote:



Goedemorgen @maartenmarx<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaartenmarx&data=05%7C01%7CM.J.Marx%40uva.nl%7Ca87ec20732a348c44ec108da2e71aa17%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637873363523580096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wgpz6MVQKx3m2Erxrlj1lEVLnbm3M9NqdhZ6LJ%2FKhjY%3D&reserved=0> ,

Ziet er goed uit! Drie dingen die me allereerst opvielen

  *   Ik denk dat we nog iets duidelijker moeten maken in de rest van het stuk aan wélke FAIR principes waarmee worden voldaan, dus er komt nu terug in het stuk dat de vier principes enorm abstract zijn, maar daarna komen ze eigenlijk individueel niet meer terug. Bijv: voorwaarde 3 zorgt voor vindbaarheid, maar ook herbruikbaarheid. Dus eigenlijk weer wat meer een terugkoppeling op die kwaliteit die genoemd is in de inleiding
  *   Voorwaarde 1 lijkt nog wat uitleg nodig te hebben (met de 'informatie-eendheid' en 'technische bestandseenheid'), we moeten onthouden dat het economen zijn die dit lezen en geen informatici, ik vind hem zelf al wat lastig te begijpen
  *   Onder 'Hoe WOB dossiers FAIR te maken' staat "en de metadata op een uniforme wijze in een spreadsheet, liefst met hyperlinks naar de losse documenten". Dat klopt niet helemaal met mijn onderzoek toch? Daar doe ik het juist niet in een spreadsheet... En de hyperlinks zijn voor ambtenaren lastig in te vullen vóór publicatie.

Nog een paar nuttige links naar onderzoeken

  *   van Oostveen & van Loenen<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepository.tudelft.nl%2Fislandora%2Fobject%2Fuuid%3A058adf5b-e824-4d1a-92e3-a6bbdd473998%3Fcollection%3Dresearch&data=05%7C01%7CM.J.Marx%40uva.nl%7Ca87ec20732a348c44ec108da2e71aa17%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637873363523580096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ddnWqbScGdGb7VPIB2VCpU2bgnUvUtqVPRUBh5Dt9%2Bs%3D&reserved=0>. Gebruikersperspectief van de WOB. Takeaway: de reacties van de overheidsorganen zijn zo verschillend (gemeleerd) dat er geen lijn in de geleverde informatie is te vinden.
  *   Actieplan open overheid 2020-2022<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.open-overheid.nl%2Factieplan-open-overheid-2020-2022%2F&data=05%7C01%7CM.J.Marx%40uva.nl%7Ca87ec20732a348c44ec108da2e71aa17%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637873363523580096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jMd%2Bk13%2FRgX4Hs8J6srcy%2Bz08ERSjhI8ER7opZBylz8%3D&reserved=0>. Takeaway: de wens voor open-wob standaarden om makkelijker overheidsinformatie te publiceren.
  *   Berenschot<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.informatiehuishouding.nl%2Fbinaries%2Finformatiehuishouding%2Fdocumenten%2Frapporten%2F2021%2F04%2F07%2Fverbeterpunten-informatiehuishouding-wob_rddi%2FRapport%2BBerenschot%2BVerbeterpunten%2BIHH%2Bivm%2Bgoede%2Bafhandeling%2BWOB-verzoeken.pdf&data=05%7C01%7CM.J.Marx%40uva.nl%7Ca87ec20732a348c44ec108da2e71aa17%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637873363523580096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pd8NtRl9lmS0fsLchb%2BsNmYduYIAaCN5reKM6HXQbsE%3D&reserved=0> volgens mij is dit dat rapport van Berenschot.

Mijn taken

  *   Hierboven stuurde ik al kort een grafiek met het aantal woorden per optie. Deze zal ik nog even finetunen.
  *   Ik heb even gekeken naar een histogram waarin we de hoeveelheid kolommen kunnen neerzetten. Dit ziet er leuk uit, maar ik twijfel nog even over de validiteit omdat er bijvoorbeeld ook wel eens tabellen 90 graden gedraaid staan, wat resulteert in 12 kolommen omdat hij dan eigenlijk het aantal rijen telt... Of redelijk vaak 1 kolom omdat, hoewel ik wel wat heb ingebouwd om dit te voorkomen, soms de tabel zo'n vreemde structuur heeft dat hij niet de rij met de kolomnamen pakt maar een lege rij. Ik zie zo 123 even niet hoe we dit kunnen oplossen. Gewoon accepteren en benoemen dat het sowieso slecht te lezen is? Ideeën?
  *   We wilden kijken hoeveel van de Openstate pdf's niet te lezen waren (met pdftotext). Ik heb wel de data gevonden, maar deze zijn helaas nog wel op WOB niveau. Dat betekent dat ik eerst zelf weer de pdf's moet downloaden, wat waarschijnlijk best simpel kan maar ik geloof dat we deze pdf al ergens hadden toch? Had Sam die niet al? Ik lijk de toegang tot Surf helaas verloren te zijn...
[image]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F54892350%2F166887097-f4f693ba-ee7d-49a8-8e32-d7db1d51a499.png&data=05%7C01%7CM.J.Marx%40uva.nl%7Ca87ec20732a348c44ec108da2e71aa17%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637873363523580096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z3Hay2PtdV3%2BHg1dRj8kfSyvybmtTSgg%2B2SJtJfcYIQ%3D&reserved=0>

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

* Dank, ik gebruik je commentaar zeker. Ik mail je de laatste PDF effe.
* Voor de inventarislijsten: ik denk dat ik de dict met varianten gebruik. Heb je allicht ook aantallen per voorkomen?
* Dus dan hebben we wat ik eerder vroeg en je hierboven beschrijft niet meer nodig.
* Je kan nu bij openstate. En wobcovvid staat hier: <https://surfdrive.surf.nl/files/index.php/s/nzDFAjykbmX3cSj> Dit komt allemaal van VWS.

OK, dan kom je er wel uit denk ik.

groetjes
maarten

**Comment by maiklarooij** [comment]
Hi @maartenmarx ,

- Ik zie de laatste PDF wel tegemoet
- Aantallen per voorkomen [hier](https://github.com/maiklarooij/bachelorsthesis/blob/master/data/columnheaders_raw.csv) in een csv
- Openstate pdfs zijn helaas totaal niet compleet in de surfdrive. Ik krijg het op een andere manier ook nog niet zo goed voor elkaar. Ik probeerde het net even met wat andere wobs van rijksoverheid.nl/documenten maar dat duurde een eeuwigheid. Is het de moeite waard om het per ministerie uit te splitsen? Het gaat me vermoedelijk aardig wat tijd kosten om iets bruikbaars te gaan krijgen. Tijd die ik ook graag in het schrijven wil stoppen aankomende weken...

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

OK bedankt joh. Ik ga even achter de openstate aan. We moeten dit even anders gaan doen.

Kan je mij het adres van je notebook sturen waarin je die pdftotext tellingen per pagina  doet? Dat was toch zo'n oneliner waar je zo trots op was ;-)

ciao
maarten

**Comment by maiklarooij** [comment]
Zeker, die staat [hier](https://github.com/maiklarooij/bachelorsthesis/blob/master/notebooks/covid19ocr.ipynb).

**Comment by maartenmarx** [comment]
;-) o ja, dat is nog net effe wat meer dan een 1 liner ;-)

Ik had gewoon lekker pdftotext-stdout|wc willen doen. Nou ik kijk wel effe. Dank in ieder geval. Dat van jou is natuurlkijk veel mooier.

**Comment by maiklarooij** [comment]
@maartenmarx hier nogmaals de [link naar het OCR notebook](https://github.com/maiklarooij/bachelorsthesis/blob/master/notebooks/covid19ocr.ipynb).

**Comment by maartenmarx** [comment]
Dank @maiklarooij , ik heb net de wat mij betrft eind versie hier neer gezet: <https://github.com/maiklarooij/bachelorsthesis/blob/master/research/ESB%20draft%20Fair%20Wob%20dossiers.pdf>

**Comment by maiklarooij** [comment]
Een kleine opmerking: onder punt 2 van de voorwaarden staat dat OCR op 77% van de pagina's extra tekst vindt, dat klopt niet. pdftotext levert juist op 77% van de pagina's wel tekst op, op 23% is geen tekst gevonden. 

Voor de rest klinkt het als een logisch verhaal toch ;)? Die tabel met verschillende gebruikte varianten is mooi, die heb ik afgelopen weekend ook in de scriptie gezet.

En nu? ESB benaderen?
