### ISSUE TITLE
Winst in informatie

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#16]
Hi @maartenmarx ,

Ik ben voor nu wel eventjes aangekomen bij het schrijven van het volgende deel over de 'winst in informatie' door mijn schema. In ons vorige gesprek hadden we het nog heel kort even over hoe ik dat het beste kan aanpakken. Het lijkt mij goed om in ieder geval te laten zien wat de winst is als enkel de verplichte velden worden ingevuld. Daarnaast schrijf ik graag iets over de kolomnamen uit de inventarislijsten. Klinkt dat als een goed idee? Dan is het een beetje verdeeld op publicatie-niveau (verplichte velden publicatie) en document-niveau (inventarislijsten). Dat is een verdeling die ik eerder ook al eens heb aangehouden. Daarin komen natuurlijk ook de FAIR principes weer lekker terug. 

Ik vraag me nog wel even af, hoe zouden we het beste de 'winst in informatie' kunnen definiëren of uitrekenen... Misschien kunnen we ergens deze week of begin volgende week even bellen over de volgende stappen? Komt er toevallig nog een Zoom moment binnenkort?

Groetjes,
Maik

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

* die tweedeling die je noemt klinkt goed.
* Een van de manieren om die wionst te laten zien is met behulp van natuurlijke informatiebehoeftes, die nu makkelijk formaliseerbaar zijn. Bijv (op mijn parlementairse stukken) Ik wil graag de debatten waar wilders onderbroken wordt door Pechtold wanneer wilders het over migratie heeft. 
   * Je kan vooral denken aan een burger die iets wil weten, en als hij het terugvindt geen wob verzoek indient.
   * en aan een wob ambtenaar die al eerdere wobstukken hoopte te kunnen hergebruiiken.
* We kunnen vanochtend even zoomen. Ik kan tot 13:30.

### openstate

* Dat openstate corpus staat nu wel op de surfdrive, in een zip bestand. Dus als je nog zou willen tellen per ministerie, heerlijk! 

groet
maarten

**Comment by maiklarooij** [comment]
@maartenmarx Fijn! Zullen we dan 11 uur doen? Zoom: https://uva-live.zoom.us/j/84528766771.
Ik maak dan even een overzichtje met de stand van zaken.

**Comment by maartenmarx** [comment]
Ja leuk, tot zo! Ik zou graag je latex/scriptie deel zien over het quality control, want dat is dan eigenlijk de lange versie van ons ESB stuk toch? Eens kijken wat voor gaafs ik er allemaal uit kan vissen ;-)

**Comment by maartenmarx** [comment]
Weet je wat, ik vraag die Serv van openstate als tweede examinator! Wat denk je daarvan? Joh, dat mag allemaal bij de bachelor IK.

**Comment by maiklarooij** [comment]
@maartenmarx 

Ik heb een eerste stuk geschreven over de informatiebehoeften. Het is [hier](https://github.com/maiklarooij/bachelorsthesis/blob/master/research/thesis%20parts/evaluationDoc.pdf) te vinden. Wat denk je ervan? In de goede richting? Volgens mij laat het al wel aardig zien dat het nu allemaal niet machine leesbaar is en vooral niet FAIR... Let vooral niet op de opmaak!

Bedankt alvast!
