### ISSUE TITLE
jouw schema nu voor alle wob datasets

### ISSUE THREAD

**Issue by maartenmarx** [maiklarooij/bachelorsthesis#17]
@maiklarooij , we hebben nu een flinka antal wob corpora, in allerlei gedaantes.

Het is mooi als we nu prob eren om die in 1 gemeenschappelijk formaat te krijgen. En jouw formaat lijkt daar dus ideaal voor.

1. Jij doiet dat al voor zonneweide
2. Sam zou dat kunnen doen/heeft dat al gedaan? voor het openstate corpus
3. Yunus heeft nu openoverheid oid leeggetrokken, en zou dat dus ook kunnen doen
4. Ruben zou het voor de document challenge kunnen doen.

Hoe krijgen we dit voor elkaar?  Voor jou is dit een mooie testcase, en ook een leuke tabel voor in je scriptie (hoeveel van de velden zijn automatisch te vullen?).

* Kan jij je spulletjes over je schema bij elkaar zetten, even helder toelichten, en toegankelijk maken (allicht nu via jouw githb repo)?
* Nu zalje merken dat zo'n fijn uitgewerkt voorbeeld enorm kan helpen ;-)
* Leg ook goed de validator uit. Geeft die behulpzame foutmeldingen? Zo nee, zorg dat dag wel gebeurt!
* Ga misschien eens met ze 4en bij elkaar zitten in een soort hackaton waarbij jullie prob eren in een paar uurtjes ieder zijn eigen corpus in jouw dformaat te krijgen.
* Voordelen zijn legio! Voor iedereen. 

Roep jij iedereen bij elkaar?

**Comment by maiklarooij** [comment]
Goed idee!

**Comment by maartenmarx** [comment]
Gaaf dat je het meteen oppikt!  Ik hoop dat het wat wordt!
