### ISSUE TITLE
Onderzoeksvoorstel

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#2]
Vóór vrijdag 26 maart 2021 23.59 uur moet er een onderzoeksvoorstel zijn ingeleverd. Het voorstel moet ongeveer twee tot vier pagina's beslaan en voldoen aan de volgende eisen:

- De context van de studie;
- Een beschrijving van de doelstelling en de relevantie van het onderzoek;
- Een sturende vraagstelling;
- Een indicatie van de literatuur die gebruikt is en gaat worden;
- Een onderzoeksplan inclusief methodesectie;
- De naam van de afstudeerbegeleider(s);
- De omvang van het onderzoek (in EC);
- Een planning inclusief wederzijdse afspraken tussen begeleider en student: daar staat in ieder geval de afspraak in dat het eindverslag zal worden opgeleverd op uiterlijk de vrijdag voorafgaand aan de laatste week van het semester. Ook is opgenomen de aard, de frequentie en de omvang van de begeleiding en de verplichtingen van de student. 

Het onderzoeksvoorstel moet door de begeleider worden goedgekeurd en ondertekend.

**Comment by maiklarooij** [comment]
@maartenmarx 

Dit heeft niet zoveel haast, maar ik heb een eerste versie van het onderzoeksvoorstel geschreven. Hij staat [hier](https://github.com/maiklarooij/bachelorsthesis/blob/master/research/12761915-Research_Proposal.pdf). Wat denk je ervan? Missen er nog dingen? Om het op 1 april in te leveren heb ik een goedkeuring en ondertekening nodig. De bijgevoegde planning is ontzettend ruim allemaal, maar ik weet het nu ook nog niet allemaal precies in te vullen :)

**Comment by maartenmarx** [comment]
Hi @maiklarooij , dit ziet er gedegen uit joh, en eenhoop is fijn herbruikbaar. Hie wat belangrijke punten: Die gaan eigenlijk alleen over je manier van formuleren: de rixhting is perfect. Dus stop er nog een uurtje of 2 in, en lever het in. Die Imke doet hier toch niet veekl mee hoor. 

groet
maarten

1. deadline die ik aanhou is laatste vrijdag van Juni. Ik denk dat jij dat makkelijk haalt. 
2. Je goals en vragen
   * de software is vaag: want niet duidelijk of het nou om producenten of consumenten gaat, en ook niet of het per wob, of juist over alle wobs gaat. Baak jouw deel af, en geef aan wat Sam gaat doen, en dat jullie dat juist op elkaar willen afstemmen.
   * Subvraag 2: geef aan hoe je wilt extracten: als je "met de hand bedoelt" zeg dan "welke informatie bevat". Ik denk dat dat veel belangrijker is: je geeft dan de bovengrens aan van wat ze allemaal vrij zouden kunnen geven.
   * RQ3 is ook veel te vaag, maar de intentie is goed. Schrijf iets over een optimale standaard, zowel voor productie, als zoekmachine als dat het alle informagtie uit RQ2 goed kan opslaan. Zoiets. Komt wel goed. **Je wilt vragen hebben met een helder antwoord. Dat schrijft veel fijner enm leest fijner en dus wordt je cijfer hoger ;-)**
   * RQ4 idem: maak het specifieker, en evalueerbaar.
2. Ik mis de kwaliteistmeting die je doet. Waarin je dus "wat mogelijk zou moeten zijn" legt naast de werkleijkheid. Dat heb heb je al gedaan, en dat is hgeerlijk om te doen, en heel makkelijk te schrijven, en erg overtuigend, zo'n dropog tabelletje met alle dingen die NIET vrijgegeven worden (en daarnaast allicht met hoeveel moeite en gedoe en wat vor kwaliteit je het er dan toch uit kan peuren met AI technieken, etc).

**Comment by maiklarooij** [comment]
@maartenmarx hartelijk dank voor de fijne, kritische en nuttige feedback. Ik ga ermee aan de slag! De kwaliteitsmeting is een goede, ik schaarde hem nu een klein beetje onder de tweede vraag, maar dat is natuurlijk nog helemaal geen vergelijk met de standaard!

**Comment by maiklarooij** [comment]
@maartenmarx 

Nieuwe versie: [hier](https://github.com/maiklarooij/bachelorsthesis/blob/master/research/12761915-Research_Proposal.pdf).
Ik heb een aantal onderzoeksvragen aangepast, maar ik verwacht dat die nog wel wat bijgeschaafd gaan worden gaandeweg. Voor nu moet ik deze gewoon even inleveren voor Imke. 

Er staat dat het goedgekeurd en ondertekend moet worden door de begeleider. Ik weet niet precies hoe, maar misschien een digitale handtekening eronder plakken 😆 ?
