### ISSUE TITLE
wob  software

### ISSUE THREAD

**Issue by maartenmarx** [maiklarooij/bachelorsthesis#20]
Hi @maiklarooij ,

In ons ESB sctuk schrijven we 

>Wij hebben dat simpel opgelost door  gratis software beschikbaar te stellen waarmee men heel handig een Wob dossier opbouwt en automatisch uniform en FAIR publiceert. De toegekende metadata zijn een uitbreiding van het voorstel door Openstate, de provincie NoordHolland en de VNG [@handrijking2021].

Ik vind eigenlijk dat we dan moeten kunnen linken naar een io.github of een andere plek waar eventjes netjes alles van die software staat, en een mooi uitgewerkt voorbeeld (jouw zonneweide natuurlijk). 

Voro je scriptie is dit ook prima. Als dit er netjes staat, kan je ernaar verwijzen, en het in je scriptie slechts summier bespreken. 

Zorg dat als men het download, dat er ook een voorbeeld meekomt, dat je dan kunt runnen, en dat je dan krijgt wat jij belooft.

**Comment by maiklarooij** [comment]
@maartenmarx komt voor elkaar! github.io gaat niet werken omdat het op de achtergrond op Python draait. Ik zal wel eens kijken of ik het mbv Heroku kan publiceren. Dan hebben we dus een Git repo met alle code/documentatie en een draaiend voorbeeld in de vorm van een webpagina.

**Comment by maiklarooij** [comment]
@maartenmarx 

- [Github repository van de software](https://github.com/maiklarooij/woopublish)
- [Webpagina online gezet met Heroku](https://woopublish.herokuapp.com/)

Is dit wat je ongeveer bedoelde? Een verdere uitwerking van een voorbeeld kan ik uiteraard later nog toevoegen. Ik heb ook een 'voorbeeld publicatie' toegevoegd, dus hoe het idealiter eruit zou zien bij publicatie: een map met documenten en een map met metadata bestanden. De JSON zou je weer in de validator van de tool kunnen gooien en dan komt die resultaatpagina er weer uit.

**Comment by maartenmarx** [comment]
He, geweldig @maiklarooij !! Heel gaaf gelukt.

Probeer nog in de werkende app ook je voorbeelden te zetten, en dat mensen dat dus kunnen bekijken/nadoen, zonder dat eerst te downloaden, en erin te ztten, maar dan gewoon klikken. 

Het is nu wat intimiderend, maar je hebt een heel mooi voorbeeld! 

Dus vooral de validator, en op een of andere manier het resultaat van alles invullen (zonder dat je dat dan hoeft te doen). 

Probeer het eens! En bespreek het eens met Sam of nog liever Filipp, die kan zich goed inleven in "simpele zielen".
succes
maarten

**Comment by maiklarooij** [comment]
@maartenmarx 

Naam is veranderd naar 'WooFAIRify' in plaats van het nietszeggende 'Woopublish' en in lijn met mijn scriptie. Dat betekent dat het ESB stuk ook even aangepast moet worden:

repository is nu: github.com/maiklarooij/wooFAIRify
link naar de demo is nu: woofairify.herokuapp.com

**Comment by maartenmarx** [comment]
Goed idee @maiklarooij , ik zie uit naar je scriptie joh! Groet maarten
