### ISSUE TITLE
Scriptie draft

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#24]
Beste @maartenmarx ,

Zoals eerder gezegd heb ik nu wel aardig een eerste draft op papier staan. Het overleaf project is [hier](https://www.overleaf.com/read/bzjpjvddmxhn) te vinden. [Hier](https://github.com/maiklarooij/bachelorsthesis/blob/master/research/ThesisDraft_Maik_Larooij_2022.pdf) is hij eventueel nog in pdf vorm. Het is zeker nog niet perfect, en ik ga hem deze week zelf ook nog een keer goed en kritisch doorlezen. Toch stuur ik hem alvast. Ik ben benieuwd naar wat je ervan vindt! Vooral naar wat nog meer uitleg nodig heeft (of juist te veel uitleg heeft ;)). En om voor te zijn dat ik straks aan het einde toch helemaal de plank heb misgeslagen (wat ik in grote lijnen niet denk). Er staan vast nog een aantal schrijffouten en dergelijke in, het gaat nu vooral even om het verhaal.

Het is fijn om iets 'definitiefs' op papier te hebben. De komende 2/3 weken kan ik dan echt bezig met verbeteren.

Geen haast, ik hoor het binnenkort wel een keer!
Groet, Maik

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

Ik kan je overleaf nie editen anders had ik zelf wel even dit erin gezet.

kan jij dat doen?

\usepackage{lineno}
\linenumbers

Dat is wat makkelijker voor commentaar he? ;-)

**Comment by maiklarooij** [comment]
Consider it done :)

**Comment by maartenmarx** [comment]
Hi @maiklarooij , geweldig werk joh! Ik ga die enthoven ook vragen.
Mijn commentaar in <https://github.com/maiklarooij/bachelorsthesis/blob/master/personal/review%20thesis%20Maik%20larooij.md>

misschien wil je morgen nog afspreken om te laten zien hoe je de lastigste van mijn puntjes hebt aangepakt.

groet
maarten
