### ISSUE TITLE
post FAIRificatie

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#25]
Hi @maartenmarx ,

Ik heb de evaluatie van de FAIR dossiers iets aangepast. Het volgt nu de volgende volgorde:
1. Introductie voorbeeld Zonneweide Jaagweg en huidige manier van publicatie
2. Omzetten van een dossier naar het JSON formaat
3. Tabel met evaluatie per FAIR principe op dit dossier
4. Introductie WooFAIRify (tool)
5. Manier van publiceren -> zelfde dossier als in punt 2 omzetten via de tool en een wijze van publiceren introduceren (die boomdiagram)

Zou je misschien nog eens willen kijken naar deze volgorde en het verhaal in https://www.overleaf.com/read/bzjpjvddmxhn

Bedankt!
Maik

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

Joh, dit is enorm verbeterd, en wat mij betreft compleet en echt heel ertg goed. Vooral je tabel is nu veel overtuigender geworden. De volgorde is logisch, en alle aspecten behandel je, en als ik dacht he, zou die tool dit ook kunnne, dan verdomd, op de volgende bladzij laat je zien dat ie dat inderdaad kan! 

Wat mij betreft lever je het in. Ik zag ook overal kleine puntjes uit mijn waslijst terug. Dus ik neem aan dat het volledig is. 

Nog even de samenvatting!

**Comment by maiklarooij** [comment]
Bedankt @maartenmarx ! Ik ga het inderdaad ergens deze week inleveren. Nog even een keer goed doorlezen en een samenvatting erbij. En dan nadenken over de presentatie...
