### ISSUE TITLE
Taal van het project

### ISSUE THREAD

**Issue by maiklarooij** [maiklarooij/bachelorsthesis#6]
Hi @maartenmarx ,

@Sambijhouwer en ik zitten een beetje in dubio over de taal van onze scripties. Aan de ene kant hebben we een lichte voorkeur voor Engels, aan de andere kant is het soms best vervelend om in het Engels te schrijven over vooral Nederlandse regelgeving en benamingen. 

Wat denk jij?

**Comment by maartenmarx** [comment]
@maiklarooij  @Sambijhouwer , heel goed punt. Ik zou het toch in het engels doen. Helemaal als we iets willen publiceren (wat me een haalbaar streven lijkt) is engels natuurlijk al veel makkelijker.

Maar laat in je tabellen etc nu gewoon de NL termen staan joh. Ga er dus heel makkelijk mee om, en doie het gewoon tweetalig, als het engels erg in de weg zit.

Komt goed! 
groetjes
maarten

**Comment by maiklarooij** [comment]
Lijkt me prima! Ik ga het schema inderdaad nog wel even omzetten naar het Engels.
