### ISSUE TITLE
FTM schema

### ISSUE THREAD

**Issue by maartenmarx** [maiklarooij/bachelorsthesis#9]
Hi @maiklarooij , via Filipp kwam ik hiermee in aanraking. Kan jij eens kijken in hoeverre je hierbij kungt aansluiten?
Ook nav mijn eerdere boodschap over dublin core en FOAF.

Maik, je eerdere werk is zeker niet waardeloos hoor! Nu s het eigenlijk gewoon een kwestie van "vertalen": kijken waarop je jouw attributen het beste kunt linken in zo'n al bestaand schema. Het maakt wat je bedoelt en wilt ook een stuk duidelijker, en het fijne is dat jij dan de betekenis van die attributen niet meer hoeft uit te legegn ;-)

succes
maarten

**Comment by maiklarooij** [comment]
Hi @maartenmarx , hoort er iets van een link bij?

**Comment by maartenmarx** [comment]
Oh sorry <https://docs.alephdata.org/developers/followthemoney>

**Comment by maiklarooij** [comment]
@maartenmarx

Ik heb het even bekeken. Ze hebben een 'document' entity met heel basis gegevens (en ik denk dat we de belangrijkste gegevens ook al hebben, zoals filename, title, language). Een wob-verzoek zelf hebben ze natuurlijk nog niet. Interessant is wel hun manier van opslaan, het is meer linked, en ze gebruiken geloof ik ook veel RDF/XML. Dat vind ik wel wat lastig, omdat dit ervoor zorgt dat je alles op verschillende plekken moet opslaan (dus 'verzoek', met verwijzingen naar 'documenten' en misschien zelfs wel 'project' dat dan weer verwijst naar 'verzoek'). Dat wordt naar mijn mening voor dit doeleinde misschien wat complex, en het is dan misschien simpeler voor de eindgebruiker (en de behandelaren) dat het in één document is op te slaan en dat het nog een beetje leesbaar is, dus dat je de documenten ook echt onder het verzoek ziet staan ipv alleen een verwijzing... We moeten niet vergeten dat de gebruikers van het schema waarschijnlijk niet allemaal ICT experts zijn die direct deze manier van opslaan begrijpen.

Wat ik wel nog even verder wil bekijken: https://followthemoney.readthedocs.io/en/latest/entity.html.
Ze hebben daar een manier van opslaan in JSON staan, en wat fijn is is dat je kunt aangeven (met een 'schema') wat voor soort entity het is. Op die manier zouden we ook beter een project als Zonneweide kunnen opslaan. Misschien kan ik delen hiervan gebruiken in mijn eigen schema. 

```
{
    "id": "passport-entity-id",
    "schema": "Passport",
    "properties": {
        "holder": ["person-entity-id"],
        "number": ["CJ 7261817"]
    }
}
```

Ik ben het sowieso eens dat ik nog even moet kijken naar de benaming van sommige attributen, en daarbij ga ik ook even kijken naar hoe FTM attributen van een document opslaat. Ik ben wel benieuwd, ben je het met me eens dat deze 'linked' manier van opslaan misschien wat te complex wordt voor dit doeleinde? Misschien heeft @Sambijhouwer ook nog goede inbreng in hoe we het beste een zoekmachine kunnen voeden.

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

even kort: ik ben het met je eens over de RDF. Jouw manier in een boom is veel beter. Je zou wel, als je die attributen niet over kan nemen uit dublin core of foaf, of ietsd anders veel gebruikt, hun *namen* voor de attributen kunnen overnemen (allicht met een ftm namespace.

groet
maarten

**Comment by maiklarooij** [comment]
@maartenmarx zeker, ook namen van Dublin Core zien er goed uit om te gebruiken. Ik twijfel nog wel een beetje over het gebruik ervan. Als ik bijvoorbeeld het volgende zou doen:

```
"dc:title": "Wob-verzoek over blah blah"
```
Maakt het het dan ook niet onnodig gecompliceerd? Misschien zou ik in mijn thesis wel kunnen noemen waar de attribuutnamen vandaan komen, maar zelf geef ik dan toch de voorkeur aan gewoon `"title": "Wob-verzoek over blah blah"`. JSON ondersteunt ook niet echt het gebruik van namespaces... Het levert zelfs soms problemen op met JSON Schema, het validatie mechanisme van JSON. Lees [dit artikel](http://lists.xml.org/archives/xml-dev/201506/msg00024.html) maar eens, interessant!

Mijn voorstel: specificaties als foaf en dublin core gebruiken om goede unieke namen te verzinnen, noemen en naar refereren in mijn thesis, maar in het echte schema geen gebruik maken van namespaces.

**Comment by maartenmarx** [comment]
Hi @maiklarooij ,

Joh, wat een gedoe. Ik raad je toch aan die namespaces te gebruiken en de cvolle naam dus. 
En dan als je dingen uit het ftm schema overneemt dat dan met ftm: te prefixen, en allicht ook een eigen namespace te maken (wob: of fia: ??)  Het is ook een mooie manier om dingen te ordenen, en te verwijzen.
Die paar karakers extra maken echt niks uit.
